length_str =input("enter length of rectangle")
width_str =input("enter width of rectangle")
length = int (length_str)
width = int(width_str)
print(f"length : {length}")
print(f"width : {width}")
area=length*width
print(f"area of rectangle is {area}")
perimeter= (length*2)+(width*2)
print(f"perimeter of rectangle is {perimeter}")